apiVersion: v1
kind: ServiceAccount
metadata:
  name: arts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: arts
  name: arts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arts
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: arts
    spec:
      securityContext: 
        runAsNonRoot: true 
        seccompProfile: 
          type: RuntimeDefault 
      serviceAccountName: arts
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/arts/arts:latest
        name: arts
        env:
        - name: ARTS_ANSIBLE_HOST
          value: "controller-service.aap.svc.cluster.local"
        - name: ARTS_ANSIBLE_USER
          value: "admin"
        - name: ARTS_ANSIBLE_PASSWORD
          value: ""
        ports:
        - containerPort: 9090
        securityContext: 
          allowPrivilegeEscalation: false 
          capabilities: 
            drop: 
              - ALL
--- 
apiVersion: v1
kind: Service
metadata:
  name: arts
spec:
  selector:
    app: arts
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: arts
spec:
  to:
    kind: Service
    name: arts
    weight: 100
  port:
    targetPort: 9090
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None